/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp_makeupsolution.SwingApplication.View;

import java.util.List;
import javaapp_makeupsolution.Controller.ClienteDAO;
import javaapp_makeupsolution.Model.Cliente;
import javaapp_makeupsolution.Model.Agenda;
import javaapp_makeupsolution.Model.Endereco;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vdsbt33
 */
public class ClienteAgenda_Editar extends javax.swing.JFrame {

    private static ClienteAgenda_Editar self = null;
    private static Cliente cliente = null;
    
    /**
     * Creates new form ClienteAgenda_Editar
     */
    private ClienteAgenda_Editar() {
        initComponents();
    }
    
    public static ClienteAgenda_Editar getSelf(Cliente alvo){
        if (self == null){
            self = new ClienteAgenda_Editar();
        }
        
        cliente = alvo;
        
        return self;
    }
    
    public static ClienteAgenda_Editar getSelf(){
        if (self == null){
            self = new ClienteAgenda_Editar();
        }
        
        return self;
    }
    
    public void atualizarCampos(){
        
        if (cliente != null){
            nomeListarTbox.setText(cliente.getNome());
            DefaultTableModel model = (DefaultTableModel) clientesTable.getModel();
            model.setRowCount(0);
            
            Object[] columnsName = { "id", "Nome", "Descricao", "Endereco" };
            model.setColumnIdentifiers(columnsName);
            
            Object[] rowData = new Object[4];
            rowData[0] = cliente.getCod();
            rowData[1] = cliente.getNome();
            rowData[2] = cliente.getDescricao();
            if (ClienteDAO.hasEndereco(cliente)){
                Endereco enderecoCliente = ClienteDAO.getEnderecoCliente(cliente);
                rowData[3] = enderecoCliente.getCidadeEndereco().getNomeCidadeEndereco() + ", " + enderecoCliente.getBairroEndereco().getNomeBairroEndereco() + ", " + enderecoCliente.getRuaEndereco().getNomeRuaEndereco() + ", " + enderecoCliente.getNumeroEndereco();
            }
            model.addRow(rowData);
            rowData[3] = "";
            
        }
    }
    
    public void limparCampos() {
        nomeListarTbox.setText("");
        DefaultTableModel model = (DefaultTableModel) clientesTable.getModel();
        model.setRowCount(0);
    }
    
    public static Cliente getCliente(){
        return cliente;
    }
    
    public static void setCliente(Cliente alvo){
        cliente = alvo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeListarTbox = new javax.swing.JTextField();
        atualizarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        guardarAgendaBtn = new javax.swing.JButton();
        cancelarAgendaBtn = new javax.swing.JButton();

        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agenda - Editar");

        jLabel2.setText("Buscar por nome:");

        atualizarBtn.setText("Buscar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtn_onClick(evt);
            }
        });

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Descrição", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clientesTable);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        guardarAgendaBtn.setText("Guardar");
        guardarAgendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAgendaBtn_onClick(evt);
            }
        });
        jPanel1.add(guardarAgendaBtn, new java.awt.GridBagConstraints());

        cancelarAgendaBtn.setText("Cancelar");
        cancelarAgendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAgendaBtn_onClick(evt);
            }
        });
        jPanel1.add(cancelarAgendaBtn, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeListarTbox, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeListarTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtn_onClick

        List<Cliente> clientes = ClienteDAO.getClienteByName(nomeListarTbox.getText());
        DefaultTableModel model = (DefaultTableModel) clientesTable.getModel();
        model.setRowCount(0);
                
        if (!clientes.isEmpty() && !nomeListarTbox.getText().isEmpty()){
            
            Object[] columnsName = { "id", "Nome", "Descricao", "Endereco" };
            model.setColumnIdentifiers(columnsName);
            
            Object[] rowData = new Object[4];
            for (int i = 0; i < clientes.size(); i++){
                rowData[0] = clientes.get(i).getCod();
                rowData[1] = clientes.get(i).getNome();
                rowData[2] = clientes.get(i).getDescricao();
                if (ClienteDAO.hasEndereco(clientes.get(i))){
                    Endereco enderecoCliente = ClienteDAO.getEnderecoCliente(clientes.get(i));
                    rowData[3] = enderecoCliente.getCidadeEndereco().getNomeCidadeEndereco() + ", " + enderecoCliente.getBairroEndereco().getNomeBairroEndereco() + ", " + enderecoCliente.getRuaEndereco().getNomeRuaEndereco() + ", " + enderecoCliente.getNumeroEndereco();
                }
                model.addRow(rowData);
                rowData[3] = "";
            }
            
        } else {
            clientesTable.removeAll();
        }
        
    }//GEN-LAST:event_atualizarBtn_onClick

    private void guardarAgendaBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAgendaBtn_onClick
        
        if (clientesTable.getSelectedRow() >= 0){
            Object rowData;
            rowData = clientesTable.getModel().getValueAt(clientesTable.getSelectedRow(), 0);

            if (rowData != null){

                cliente = ClienteDAO.getClienteByID((int) rowData);
                
                this.setVisible(false);
                Agenda_Editar.getSelf().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "É necessário selecionar um cliente.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar um cliente.");
        }
        
    }//GEN-LAST:event_guardarAgendaBtn_onClick

    private void cancelarAgendaBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAgendaBtn_onClick
        this.setVisible(false);
        Agenda_Editar.getSelf().setVisible(true);
    }//GEN-LAST:event_cancelarAgendaBtn_onClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteAgenda_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteAgenda_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteAgenda_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteAgenda_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteAgenda_Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JButton cancelarAgendaBtn;
    private javax.swing.JTable clientesTable;
    private javax.swing.JButton guardarAgendaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeListarTbox;
    // End of variables declaration//GEN-END:variables
}
