/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp_makeupsolution.SwingApplication.View;

import java.util.ArrayList;
import java.util.List;
import javaapp_makeupsolution.Controller.ClienteDAO;
import javaapp_makeupsolution.Model.Cliente;
import javaapp_makeupsolution.Model.Endereco;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author vdsbt33
 */
public class Clientes_Listar extends javax.swing.JFrame {

    private static Clientes_Listar self = null;
    
    private List<Cliente> clientes = null;
    
    /**
     * Creates new form Clientes_Listar
     */
    private Clientes_Listar() {
        initComponents();
    }
    
    public static Clientes_Listar getSelf(){
        if (self == null){
            self = new Clientes_Listar();
        }
        return self;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeListarTbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        atualizarBtn = new javax.swing.JButton();
        editarClienteBtn = new javax.swing.JButton();
        removerClienteBtn = new javax.swing.JButton();
        agendarClienteBtn = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(388, 279));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes - Buscar");

        jLabel2.setText("Buscar por nome:");

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Descrição", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(clientesTable);

        atualizarBtn.setText("Buscar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtn_onClick(evt);
            }
        });

        editarClienteBtn.setText("Editar");
        editarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteBtn_onClick(evt);
            }
        });

        removerClienteBtn.setText("Excluir");
        removerClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClienteBtn_onClick(evt);
            }
        });

        agendarClienteBtn.setText("Agendar");
        agendarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarClienteBtn_onClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeListarTbox, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agendarClienteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarClienteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerClienteBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeListarTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarClienteBtn)
                    .addComponent(removerClienteBtn)
                    .addComponent(agendarClienteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarLista(){
        clientes = ClienteDAO.getClienteByName(nomeListarTbox.getText());
        DefaultTableModel model = (DefaultTableModel) clientesTable.getModel();
        model.setRowCount(0);
                
        if (!clientes.isEmpty() && !nomeListarTbox.getText().isEmpty()){
            
            Object[] columnsName = { "id", "Nome", "Descricao", "Endereco" };
            model.setColumnIdentifiers(columnsName);
            
            Object[] rowData = new Object[4];
            for (int i = 0; i < clientes.size(); i++){
                rowData[0] = clientes.get(i).getCod();
                rowData[1] = clientes.get(i).getNome();
                rowData[2] = clientes.get(i).getDescricao();
                if (ClienteDAO.hasEndereco(clientes.get(i))){
                    Endereco enderecoCliente = ClienteDAO.getEnderecoCliente(clientes.get(i));
                    rowData[3] = enderecoCliente.getCidadeEndereco().getNomeCidadeEndereco() + ", " + enderecoCliente.getBairroEndereco().getNomeBairroEndereco() + ", " + enderecoCliente.getRuaEndereco().getNomeRuaEndereco() + ", " + enderecoCliente.getNumeroEndereco();
                }
                model.addRow(rowData);
                rowData[3] = "";
            }
        } else {
            clientesTable.removeAll();
        }
    }
    
    private void atualizarBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtn_onClick
        
        atualizarLista();
    }//GEN-LAST:event_atualizarBtn_onClick

    private void editarClienteBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteBtn_onClick
        if (clientesTable.getSelectedRow() >= 0){
            Object rowData;
            rowData = clientesTable.getModel().getValueAt(clientesTable.getSelectedRow(), 0);
            Clientes_Editar clientes_editar = null;
            clientes_editar = Clientes_Editar.getSelf(ClienteDAO.getClienteByID(((int) rowData)));
            clientes_editar.setVisible(true);
            clientes_editar.atualizarCampos();
            this.setVisible(false);
        }
    }//GEN-LAST:event_editarClienteBtn_onClick

    private void removerClienteBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClienteBtn_onClick
        if (clientesTable.getSelectedRow() >= 0){
            Object rowData;
            rowData = clientesTable.getModel().getValueAt(clientesTable.getSelectedRow(), 0);
            Cliente cliente = ClienteDAO.getClienteByID((int) rowData);
            
            if (ClienteDAO.exists((int) rowData)){
                int selectedOption = JOptionPane.showConfirmDialog(null,
                        "Tem certeza que deseja remover o cliente " + cliente.getNome() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_OPTION){
                    ClienteDAO.Remover(ClienteDAO.getClienteByID((int) rowData));
                    atualizarLista();
                    JOptionPane.showMessageDialog(null, "Cliente removido com sucesso.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "O cliente selecionado não existe.");
            }
        }
    }//GEN-LAST:event_removerClienteBtn_onClick

    private void agendarClienteBtn_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarClienteBtn_onClick
        if (clientesTable.getSelectedRow() >= 0){
            Object rowData;
            rowData = clientesTable.getModel().getValueAt(clientesTable.getSelectedRow(), 0);
            Cliente cliente = ClienteDAO.getClienteByID((int) rowData);
            
            if (ClienteDAO.exists((int) rowData)){
                    this.setVisible(false);
                    Agenda_Adicionar agendaAdicionar = Agenda_Adicionar.getSelf(cliente);
                    agendaAdicionar.limparCampos();
                    agendaAdicionar.setVisible(true);
                    
            } else {
                JOptionPane.showMessageDialog(null, "O cliente selecionado não existe.");
            }
        }
        
    }//GEN-LAST:event_agendarClienteBtn_onClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes_Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendarClienteBtn;
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JTable clientesTable;
    private javax.swing.JButton editarClienteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeListarTbox;
    private javax.swing.JButton removerClienteBtn;
    // End of variables declaration//GEN-END:variables
}
